# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  repository_dispatch:
    types: dispatch-from-docs
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
        # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'abcdesktopio/docs'
          submodules: true
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: install drawio
        run: |
          sudo apt-get update
          wget https://github.com/jgraph/drawio-desktop/releases/download/v16.5.1/drawio-amd64-16.5.1.deb
          sudo apt-get install --yes ./drawio-amd64-16.5.1.deb
          
      - name: convert drawio to svg
        run: |
          ls -la docs/opsdocs/docs/common
          /opt/drawio/drawio -x -f svg -o opsdocs/docs/common/abcdesktop.bastion.svg opsdocs/docs/common/abcdesktop.bastion.drawio 
      
      - name : install material
        run: pip install mkdocs-material
      
      - name: Run Makefile
        run: |
          mkdocs --version
          make docs
        
      - name: dump sources
        run: |
          ls -la opsdocs/site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: opsdocs/site # The folder the action should deploy.
